[package]
name = "gsf-middleware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gsf-session = { path = "../session" }
async-trait = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
